CodeWebCuaTui/Models/Cart.cs
namespace CodeWebCuaTui.Models
{
    public class Cart
    {
        public Guid ID { get; set; }
        public string Describe { get; set; }
        public virtual User User { get; set; } 
        public virtual List<CartDetails> CartDetails { get; set; }
    }
}

CodeWebCuaTui/Controllers/BillController.cs
using CodeWebCuaTui.IServices;
using CodeWebCuaTui.Models;
using CodeWebCuaTui.Services;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
namespace CodeWebCuaTui.Controllers
{
    public class BillController : Controller
    {
        private readonly ILogger<BillController> _logger;
        private readonly IUserServices _userServices;
        private readonly IBillServices _Bill;
        private readonly IBillDetailsServices _billDetails;
        private readonly ICartDetailsServices _CartDetails;
        private readonly IProductServices productServices;

        public BillController(ILogger<BillController> logger)
        {
            _logger = logger;
            _Bill = new BillServices();
            _userServices = new UserServices();
            _billDetails = new BillDetailsServices();
            _Bill = new BillServices();
            _CartDetails = new CartDetailsServices();
            productServices = new ProductServices();
        }
        //---------------Bill------------

        public IActionResult Pay(string name, string address, string phone, string Describe)
        {
            var UserID = _userServices.GetUserByName(HttpContext.Session.GetString("acc"))[0].ID;
            var listCartDetails = _CartDetails.GetAllCartDetailss().Where(c => c.UserID == UserID);
            decimal tongtien = listCartDetails.Sum(c => c.Quantity * c.Product.Price);
            var Chuoi = "";
            var outOfStockProducts = listCartDetails
                             .Where(item => item.Quantity > productServices.GetProductById(item.ProductId).Quantity)
                             .Select(item => '"' + productServices.GetProductById(item.ProductId).Name);
            Chuoi = string.Join(" ", outOfStockProducts);

            if (listCartDetails.Any())
            {
                if (Chuoi == "")
                {
                    var bill = new Bill()
                    {
                        ID = new Guid(),
                        DateCreate = DateTime.Now,
                        DateOfPay = DateTime.Now,
                        UserID = UserID,
                        Name = name,
                        Phone = phone,
                        Address = address,
                        Describe = Describe,
                        TotalAmount = tongtien,
                        Status = 0
                    };
                    _Bill.CreateBill(bill);
                    foreach (var item in listCartDetails)
                    {
                        _billDetails.CreateBillDetails(new BillDetails()
                        {
                            ID = new Guid(),
                            BillID = bill.ID,
                            ProductId = item.ProductId,
                            Quantity = item.Quantity,
                            Price = tongtien
                        });
                        _CartDetails.DeleteCartDetails(item.ID);
                        var product = productServices.GetProductById(item.ProductId);
                        product.Quantity -= item.Quantity;
                        productServices.UpdateProduct(product);
                    }
                    TempData["successful"] = "Thanh toán thanh toán thành công";
                    var cartDetailss = _CartDetails.GetAllCartDetailss().Where(c => c.UserID == UserID).ToList();
                    HttpContext.Session.SetString("CartDetailsUser", cartDetailss.Count().ToString());
                    return RedirectToAction("ShowCartUser", "Cart");
                }
                else
                {
                    TempData["PayError"] = "Thanh toán không thành công do số lượng tồn của " + Chuoi + " không đủ !!!";

                }
            }
            return RedirectToAction("ShowCartUser", "Cart");
        }
        public IActionResult PayForNoUser(string name, string address, string phone, string Describe)
        {
            Guid idUser = Guid.Parse("8896ec84-ce69-4b53-a984-efc05024d0ad");
            var lstCartDetails = SessionServices.GetObjFromSession(HttpContext.Session, "Cart");
            if (lstCartDetails != null)
            {
                decimal tongtien = lstCartDetails.Sum(c => c.Quantity * c.Price);
                var Chuoi = "";
                var outOfStockProducts = lstCartDetails
                                 .Where(item => item.Quantity > productServices.GetProductById(item.ProductID).Quantity)
                                 .Select(item => '"' + productServices.GetProductById(item.ProductID).Name);
                Chuoi = string.Join(" ", outOfStockProducts);

                if (lstCartDetails.Any())
                {
                    if (Chuoi == "")
                    {
                        var bill = new Bill()
                        {
                            ID = new Guid(),
                            DateCreate = DateTime.Now,
                            DateOfPay = DateTime.Now,
                            UserID = idUser,
                            Name = name,
                            Phone = phone,
                            Address = address,
                            Describe = Describe,
                            TotalAmount = tongtien,
                            Status = 0
                        };
                        _Bill.CreateBill(bill);
                        foreach (var item in lstCartDetails)
                        {
                            _billDetails.CreateBillDetails(new BillDetails()
                            {
                                ID = new Guid(),
                                BillID = bill.ID,
                                ProductId = item.ProductID,
                                Quantity = item.Quantity,
                                Price = tongtien
                            });
                            var product = productServices.GetProductById(item.ProductID);
                            product.Quantity -= item.Quantity;
                            productServices.UpdateProduct(product);
                        }
                        TempData["successful"] = "Thanh toán thanh toán thành công";
                        HttpContext.Session.Remove("Cart");
                        return RedirectToAction("ShowCart", "Cart");
                    }
                    else
                    {
                        TempData["PayError"] = "Thanh toán không thành công do số lượng tồn của " + Chuoi + " không đủ !!!";

                    }
                }
            }
            return RedirectToAction("ShowCart", "Cart");
        }
        public IActionResult ShowBillForAdmin()
        {
            List<Bill> billList = (_Bill.GetAllBills());
            return View(billList);
        }
        public IActionResult ShowBillForUser()
        {
            var UserID = _userServices.GetUserByName(HttpContext.Session.GetString("acc"))[0].ID;
            List<Bill> billList = (_Bill.GetAllBills().Where(c => c.UserID == UserID)).ToList();
            return View(billList);
        }
        public IActionResult ShowBillDetails(Guid id)
        {
            List<BillDetails> bills = _billDetails.GetAllBillDetails().Where(c => c.BillID == id).ToList();
            return View(bills);
        }
      
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CodeWebCuaTui/Controllers/RoleController.cs
using CodeWebCuaTui.IServices;
using CodeWebCuaTui.Models;
using CodeWebCuaTui.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
namespace CodeWebCuaTui.Controllers
{
    public class RoleController : Controller
    {
        private readonly ILogger<RoleController> _logger;
        private readonly IRoleServices _Role;
        public RoleController(ILogger<RoleController> logger)
        {
            _logger = logger;
            _Role = new RoleServices();
        }
        //---------------Role------------
        public IActionResult ShowAll()
        {
            List<Role> Role = _Role.GetAllRoles();
            return View(Role);
        }
        public IActionResult Details(Guid id)
        {
            CodeWebCuaTuiDbContex contex = new CodeWebCuaTuiDbContex();
            var Role = contex.Roles.Find(id);
            return View(Role);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Role Role)
        {
            if (_Role.CreateRole(Role))
            {
                return RedirectToAction("ShowAll");
            }
            else return BadRequest();
        }
        [HttpGet]
        public IActionResult Edit(Guid id)
        {
            Role Role = _Role.GetRoleById(id);
            return View(Role);
        }
        public IActionResult Edit(Role Role)
        {
            if (_Role.UpdateRole(Role))
            {
                return RedirectToAction("ShowAll");
            }
            else return BadRequest();
        }
        public IActionResult Delete(Guid id)
        {
            if (_Role.DeleteRole(id))
            {
                return RedirectToAction("ShowAll");
            }
            else return BadRequest();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CodeWebCuaTui/Controllers/SizeController.cs
using CodeWebCuaTui.IServices;
using CodeWebCuaTui.Models;
using CodeWebCuaTui.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
namespace CodeWebCuaTui.Controllers
{
    public class SizeController : Controller
    {
        private readonly ILogger<SizeController> _logger;
        private readonly ISizeServices _Size;
        public SizeController(ILogger<SizeController> logger)
        {
            _logger = logger;
            _Size = new SizeServices();
        }
        //---------------Size------------
        public IActionResult ShowAll()
        {
            List<Size> Size = _Size.GetAllSizes();
            return View(Size);
        }
        public IActionResult Details(Guid id)
        {
            CodeWebCuaTuiDbContex contex = new CodeWebCuaTuiDbContex();
            var Size = contex.Sizes.Find(id);
            return View(Size);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Size Size)
        {
            if (_Size.CreateSize(Size))
            {
                return RedirectToAction("ShowAll");
            }
            else return BadRequest();
        }
        [HttpGet]
        public IActionResult Edit(Guid id)
        {
            Size Size = _Size.GetSizeById(id);
            return View(Size);
        }
        public IActionResult Edit(Size Size)
        {
            if (_Size.UpdateSize(Size))
            {
                return RedirectToAction("ShowAll");
            }
            else return BadRequest();
        }
        public IActionResult Delete(Guid id)
        {
            if (_Size.DeleteSize(id))
            {
                return RedirectToAction("ShowAll");
            }
            else return BadRequest();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CodeWebCuaTui/Controllers/UserController.cs
using CodeWebCuaTui.IServices;
using CodeWebCuaTui.Models;
using CodeWebCuaTui.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using System.Net.WebSockets;
using System.Security.Principal;

namespace CodeWebCuaTui.Controllers
{
    public class UserController : Controller
    {
        private readonly ILogger<UserController> _logger;
        private readonly IUserServices _User;
        private readonly ICartServices _CartServices;
        private readonly ICartDetailsServices _CartDetailsServices;
        private readonly IRoleServices _RoleServices;
        private CodeWebCuaTuiDbContex contex;
        public UserController(ILogger<UserController> logger)
        {
            _logger = logger;
            _User = new UserServices();
            _CartServices = new CartServices();
            _CartDetailsServices = new CartDetailsServices();
            _RoleServices = new RoleServices();
            contex = new CodeWebCuaTuiDbContex();
        }
        //---------------User------------
        public IActionResult ShowAll()
        {
            var User = contex.Users.Include("Role").ToList();
            return View(User);
        }
        public IActionResult Details(Guid id)
        {
            CodeWebCuaTuiDbContex contex = new CodeWebCuaTuiDbContex();
            var User = contex.Users.Find(id);
            return View(User);
        }
        public IActionResult Logout()
        {
            HttpContext.Session.Remove("acc");
            return RedirectToAction("Login");
        }
        public ActionResult Login(string username, string password)
        {
            var products = SessionServices.GetObjFromSession(HttpContext.Session, "Cart");

            if (ModelState.IsValid)
            {
                var data = contex.Users.Include("Role").FirstOrDefault(s => s.UserName.Equals(username) && s.Password.Equals(password));
                if (data != null)
                {
                    //add Session
                    HttpContext.Session.SetString("acc", data.UserName);
                    HttpContext.Session.SetString("role", data.Role.Name);
                    var acc = HttpContext.Session.GetString("acc");
                    TempData["Message"] = "Xin chào " + acc + " đã đến với MixiShop";

                    var x = _User.GetAllUsers().FirstOrDefault(x => x.UserName == username);
                    var lstCart = _CartServices.GetAllCarts();
                    var cartDetails = _CartDetailsServices.GetAllCartDetailss().Where(c => c.UserID == x.ID).ToList();
                    HttpContext.Session.SetString("CartDetailsUser", cartDetails.Count().ToString());
                    if (lstCart.FirstOrDefault(c => c.ID == x.ID) == null)
                    {
                        Cart cart = new Cart()
                        {
                            ID = x.ID,
                            Describe = null,
                        };
                        _CartServices.CreateCart(cart);
                    }
                    HttpContext.Session.Remove("Cart");
                    return RedirectToAction("Index", "Home");

                }
                else
                {

                    TempData["AlertMessage"] = "Login failed";
                    return RedirectToAction("Login");
                }
            }
            return View();
        }
        public IActionResult Create()
        {
            ViewBag.Role = new SelectList(_RoleServices.GetAllRoles(), "ID", "Name");
            return View();
        }
        [HttpPost]
        public IActionResult Create(User User)
        {

            if (_User.CreateUser(User))
            {
                Cart cart = new Cart()
                {
                    ID = User.ID,
                    Describe = null
                };
                _CartServices.CreateCart(cart);
                TempData["Create"] = "Đăng kí thành công";
                return RedirectToAction("Index", "Home");
            }
            else
            {
                TempData["MessageForCreate"] = "Đăng kí thất bại do trùng UserName";
                return RedirectToAction("Create");
            }
        }


        [HttpGet]
        public IActionResult Edit(Guid id)
        {
            ViewBag.Role = new SelectList(_RoleServices.GetAllRoles(), "ID", "Name");
            User User = _User.GetUserById(id);
            return View(User);
        }
        public IActionResult Edit(User User)
        {
            ViewBag.Role = new SelectList(_RoleServices.GetAllRoles(), "ID", "Name");
            if (_User.UpdateUser(User))
            {
                return RedirectToAction("ShowAll");
            }
            else return BadRequest();
        }
        public IActionResult Delete(Guid id)
        {
            if (_User.DeleteUser(id))
            {
                return RedirectToAction("ShowAll");
            }
            else return BadRequest();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CodeWebCuaTui/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
    <div class="container text-center" style="margin-top:20px>
        <div class="row align-items-start">
            <div class="col-12 col-md-12">
                <h2 style="color: red;">Thông báo</h2>
            </div>
            <div class="col-12 col-md-12" align="justify" style="font-size: large;">
                MixiShop xin thông báo hiện Shop KHÔNG có chương trình tri ân khách hàng nào bằng việc tặng nước hoa,
                quà, hoặc một vài sản phẩm khác như một số bạn<br>
                đã nhận được thông tin.<br>
                <br>
                Các bạn lưu ý tránh để kẻ gian trục lợi làm ảnh hưởng uy tín của Shop nhé ạ<br>
                Số điện thoại check đơn của nhân viên MixiShop lần lượt ở dưới đây. Các bạn vui lòng kiểm tra tin nhắn
                hoặc cuộc gọi check thông tin đơn hàng có khớp với các<br>
                số này hay không nhé 😘<br>
    
             <p style="color: red;">    ☎️ Chi tiết xin liên hệ Hotline: 0822221992 / 0922222016 <p>
                Bạn nào có tin nhắn hoặc cuộc gọi về việc nhận được quà tặng từ chương trình tri ân khách hàng vui lòng
                comment vào bài đăng inbox hoặc gọi trực tiếp vào.<br>
                hotline giúp chúng mình.<br>
    
                CÓ MỘT YÊU CÂU NHỎ TRONG LẦN NÀY, CÁC BẠN QUAY LẠI VIDEO BÓC KIỆN HÀNG GIÚP SHOP. TRONG TRƯỜNG HỢP ĐỔI
                TRẢ (ĐỐI VỚI SẢN PHẨM LÀ ÁO,<br>
                YÊU CẤU PHẢI CÒN NGUYÊN TAG MAC), NHẬN THIẾU HÀNG, CÁC BẠN GỬI LẠI VIDEO ĐÓ VÀ INBOX PACE MIXISHOP ĐỀ
                ĐƯỢC HỖ TRỢ NHANH HẾT SỨC CÓ.<br>
                THỂ Ạ.<br>
                <br>
                Nếu có bất kì thắc mắc vui lòng inbox fanpage MixiShop để được giải đáp. Xin chân thành cám ơn và yêu
                thương rất nhiều<br>
    
                Hiện tại bên shop CHƯA có bất cứ chương trình tri ân nào. Nếu có ưu đãi cũng sẽ được thông báo công khai
                trên các kênh CHÍNH THỨC VÀ DUY NHẤT sau đây:<br>
               <a href="index.html">Website : https:/Shop.mixigaming.com/</a> <br>
               <a href="https:/www.facebook.com/MixiShop-l82674912585855"> Fanpage : https:/www.facebook.com/MixiShop-l82674912585855/</a> <br>
               <a href="https:/www.instagram.com/mixi.shop">Instagram : https:/www.instagram.com/mixi.shop/</a> <br>    
               
                Email: Mixiishop@gmailcom<br>
    
                MixiShop xin vui lòng được phục vụ quý khách!<br>
    
            </div>
        </div>
    </div>
   

CodeWebCuaTui/Views/Home/Admin.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="container text-center">
    <h1  >Quản trị</h1>
    <table class="table">
  <thead>
    <tr>
      <th scope="col">STT</th>
      <th scope="col">Tên bảng</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td><a asp-controller="Category" asp-area="" asp-action="ShowAll">Category</a></td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td><a asp-controller="Color" asp-area="" asp-action="ShowAll">Color</a></td>
    </tr>
      <tr>
      <th scope="row">3</th>
      <td><a asp-controller="Size" asp-area="" asp-action="ShowAll">Size</a></td>
    </tr>
     <tr>
      <th scope="row">4</th>
      <td><a asp-controller="Supplier" asp-area="" asp-action="ShowAll">Supplier</a></td>
    </tr>
     <tr>
      <th scope="row">5</th>
      <td><a asp-controller="Image" asp-area="" asp-action="ShowAll">Image</a></td>
    </tr>   
      <tr>
      <th scope="row">7</th>
      <td><a asp-controller="Product" asp-area="" asp-action="ShowAll">Product</a></td>
    </tr>
    <tr>
      <th scope="row">8</th>
      <td><a asp-controller="Role" asp-area="" asp-action="ShowAll">Role</a></td>
    </tr>
       <tr>
      <th scope="row">9</th>
      <td><a asp-controller="User" asp-area="" asp-action="ShowAll">User</a></td>
    </tr>
    <tr>
      <th scope="row">9</th>
      <td><a asp-controller="Bill" asp-area="" asp-action="ShowBillForAdmin">Bill Manager</a></td>
    </tr>
     
  </tbody>
</table>
</div>

CodeWebCuaTui/Views/Home/AoCoc.cshtml
@model IEnumerable<CodeWebCuaTui.Models.Product>

@{
    ViewData["Title"] = "AoCoc";
}
@{
    var Product1 = ViewBag.Product1 as List<Product>;
    var Product2 = ViewBag.Product2 as List<Product>;
}
<!--article  -->
    <div class="container " style="margin-top:20px;;">
        <div class="row align-items-start">
            <div class="col-4 col-md-4" style="margin: auto;">
                <h3>Áo cộc</h3>
                <a href="index.html">Trang Chủ</a>/ <strong>Áo cộc</strong>
            </div>
            <div class="col-4 col-md-4">
                <p align="right" style="padding-top: 7px;">Hiển thị 1-12 của 19 kết quả</p>
            </div>
            <div class="col-4 col-md-4">
                <select class="form-select" aria-label="Default select example">
                    <option selected>Thứ tự theo điểm đánh giá</option>
                    <option value="1">Mới nhất</option>
                    <option value="2">Thứ tự theo giá: thấp tới cao</option>
                    <option value="3">Thứ tự theo giá: cao tới thấp</option>
                </select>
            </div>
        </div>
    </div>
    <div class="container text-center" style="margin-top:20px;padding-top: 50px;">
        <div class="row align-items-start">
            <div class="col-3 col-md-3">
                <div class="card" style="width: 18rem;" align="justify">

                    <div class="card-body">
                        <label for="customRange2" class="form-label">Lọc theo giá</label>
                        <input type="range" class="form-range" min="0" max="5" id="customRange2">
                        <button type="button" class="btn btn-secondary">Lọc</button>
                        <p style="float: right;padding-top: 9px;">Giá 220.000đ - 500.000 đ</p>
                        <br><br>
                        <p class="card-text" style="font-weight: 500; font-size: larger;">Danh mục sản phẩm</p>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"><a  asp-area="" asp-controller="Home" asp-action="AoCoc">Áo cộc </a></li>
                        <li class="list-group-item"><a asp-area="" asp-controller="Home" asp-action="AoDai">Áo dài</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-9 col-md-9">
                  <div class="row align-items-start">
          @foreach (var item in Product1)
             {
               <div class="col-4 col-md-4" style="margin: auto;"  >
                 <div class="khung" style="position: relative;">
                   <img class="anhsp" style="border: 0px;width:260px;height:350px"  class="img-thumbnail" alt="..." src="@Url.Content(item.Images.Path1)"
                     alt="Hình ảnh" width="260" height="350" >
                 </div>  
                 <br>
                <p style="color: rgb(24, 1, 1);" class="theloai"> @Html.DisplayFor(modelItem => item.Category.Name)</p>
                      <a class="linksp">  @Html.ActionLink(item.Name, "Details", new { id=item.ID })</a> <br>
  @*              <a class="linksp" asp-area="" asp-controller="Home" asp-action="Details"> @Html.DisplayFor(modelItem => item.Name)</a><br>*@
                <img src="~/Image/stars.png" style="border: 0px; width: 60px;" class="img-thumbnail" alt="...">
                <p><Strong>
                     @string.Format("{0:N0}đ", item.Price)
                </Strong>
               </div>

             }
            
     </div>
                    <div class="button">
                        <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
                            <div class="btn-group me-2" role="group" aria-label="First group">
                                <button type="button" class="btn btn-primary">1</button>
                                <button type="button" class="btn btn-primary">2</button>
                                <button type="button" class="btn btn-primary">3</button>
                                <button type="button" class="btn btn-primary">4</button>
                            </div>
                            <button type="button" class="btn btn-primary">></button>
                        </div>
                    </div>
       
            </div>
    </div>

CodeWebCuaTui/Views/Home/ForgotPass.cshtml
   <section class="vh-100 gradient-custom">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                    <div class="card bg-white text-dark" style="border-radius: 1rem;">
 
                                <div class="modal-dialog" style="width: 500px;">
            <div class="modal-content text-center">
                
    <div class="card text-center" style="width: 300px;">
    <div class="card-header h5 text-white bg-primary">Password Reset</div>
    <div class="card-body px-5">
        <p class="card-text py-2">
            Enter your email address and we'll send you an email with instructions to reset your password.
        </p>
        <div class="form-outline">
            <input type="email" id="typeEmail" class="form-control my-3" />
            <label class="form-label" for="typeEmail">Email input</label>
        </div>
        <a href="#" class="btn btn-primary w-100">Reset password</a>
        <div class="d-flex justify-content-between mt-4">
            <a class="" a asp-area="" asp-controller="Home" asp-action="Login" style="font-size: 20px;">Đăng nhập</a>
                        <a class=""a asp-area="" asp-controller="User" asp-action="Create" style="font-size: 20px;">Đăng ký</a>
        </div>
    </div>
</div>
            </div>
        </div>                                    
                </div>
            </div>
        </div>
    </section>

CodeWebCuaTui/Views/Home/Login.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
   <!--article  -->
    <section class="vh-100 gradient-custom">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                    <div class="card bg-white text-dark" style="border-radius: 1rem;">
                        <div class="card-body p-5 text-center">

                            <div class="mb-md-5 mt-md-4 pb-5">

                                <h2 class="fw-bold mb-2 text-uppercase" style="font-size: 50px;">Đăng nhập</h2>
                                <p class="text-dark-50 mb-5" style="font-size: 30px;">Nhập tài khoản và mật khẩu!</p>

                                <div class="form-outline form-dark mb-4">
                                    <input type="email" id="typeEmailX" class="form-control form-control-lg" />
                                    <label class="form-label" for="typeEmailX" style="font-size: 20px;">Email</label>
                                </div>

                                <div class="form-outline form-dark mb-4">
                                    <input type="password" id="typePasswordX" class="form-control form-control-lg" />
                                    <label class="form-label" for="typePasswordX" style="font-size: 20px;">Mật
                                        khẩu</label>
                                </div>

                                <p class="small mb-5 pb-lg-2"><a class="text-dark-50"  data-mdb-toggle="modal"
                                        data-mdb-target="#exampleModal" style="font-size: 20px;" asp-area="" asp-controller="Home" asp-action="ForgotPass" >Quên mật khẩu?</a></p>

                                <button class="btn btn-outline-danger btn-lg px-5" type="submit">Đăng nhập</button>
                       
                                <div class="d-flex justify-content-center text-center mt-4 pt-1">
                                    <a href="#!" class="text-dark"><i class="fab fa-facebook-f fa-lg"></i></a>
                                    <a href="#!" class="text-dark"><i class="fab fa-twitter fa-lg mx-4 px-2"></i></a>
                                    <a href="#!" class="text-dark"><i class="fab fa-google fa-lg"></i></a>
                                </div>

                            </div>

                            <div>
                                <p class="mb-0" style="font-size: 20px;">Không có tài khoản? <a asp-area="" asp-controller="User" asp-action="Create"
                                        class="text-dark-50 fw-bold">Đăng ký</a>
                                </p>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- quen mk -->
   