CodeWebCuaTui/Models/Product.cs
namespace CodeWebCuaTui.Models
{
    public class Product
    {
        public Guid ID { get; set; }
        public Guid ColorID { get; set; }
        public Guid SizeID { get; set; }
        public Guid SupplierID { get; set; }
        public Guid CategoryID { get; set; }
        public Guid ImageID { get; set; }
        public string ProductCode { get; set; }
        public string Name { get; set; }
        public string Describe { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public int Status { get; set; }
        public virtual Category Category { get; set; }
        public virtual Supplier Suppliers { get; set; }
        public virtual Color Color { get; set; }
        public virtual Size Sizes { get; set; }
        public virtual Images Images { get; set; }
        public virtual List<CartDetails> CartDetails { get; set; }
        public virtual List<BillDetails> BillDetails { get; set; }
    }
}

CodeWebCuaTui/Controllers/ImageController.cs
using CodeWebCuaTui.IServices;
using CodeWebCuaTui.Models;
using CodeWebCuaTui.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace CodeWebCuaTui.Controllers
{
    public class ImageController : Controller
    {
        private readonly ILogger<ImageController> _logger;
        private readonly IImageServices _Image;
        public ImageController(ILogger<ImageController> logger)
        {
            _logger = logger;
            _Image = new ImagesServices();
        }
        //---------------Image------------
        public IActionResult ShowAll()
        {
            List<Images> categories = _Image.GetAllImagess();
            return View(categories);
        }
        public IActionResult Details(Guid id)
        {
            CodeWebCuaTuiDbContex contex = new CodeWebCuaTuiDbContex();
            var Image = contex.Images.Find(id);
            return View(Image);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateAsync(Images Image)
        {
            var file1 = Request.Form.Files["image1"];
            var file2 = Request.Form.Files["image2"];
            var file3 = Request.Form.Files["image3"];
            var file4 = Request.Form.Files["image4"];
            string sourcePath1 = file1.FileName;
            string sourcePath2 = file2.FileName;
            string sourcePath3 = file3.FileName;
            string sourcePath4 = file4.FileName;
            Image.Path1 = sourcePath1;
            Image.Path2 = sourcePath2;
            Image.Path3 = sourcePath3;
            Image.Path4 = sourcePath4;
            if (_Image.CreateImages(Image))
            {
                string destinationPath = @"C:\Chang\C#4\Code\CodeWebCuaTui\CodeWebCuaTui\wwwroot\Image\";
                string fileName1 = Path.GetFileName(sourcePath1);
                string fileName2 = Path.GetFileName(sourcePath2);
                string fileName3 = Path.GetFileName(sourcePath3);
                string fileName4 = Path.GetFileName(sourcePath4);
                string destinationFilePath1 = Path.Combine(destinationPath, fileName1);
                string destinationFilePath2 = Path.Combine(destinationPath, fileName2);
                string destinationFilePath3 = Path.Combine(destinationPath, fileName3);
                string destinationFilePath4 = Path.Combine(destinationPath, fileName4);
                using (var stream = new FileStream(destinationFilePath1, FileMode.Create))
                {
                    await file1.CopyToAsync(stream);

                }
                using (var stream = new FileStream(destinationFilePath2, FileMode.Create))
                {
                    await file2.CopyToAsync(stream);

                }
                using (var stream = new FileStream(destinationFilePath3, FileMode.Create))
                {
                    await file3.CopyToAsync(stream);

                }
                using (var stream = new FileStream(destinationFilePath4, FileMode.Create))
                {
                    await file4.CopyToAsync(stream);

                }
                return RedirectToAction("ShowAll");
            }
            else return BadRequest();
        }
        [HttpGet]
        public IActionResult Edit(Guid id)
        {
            Images Image = _Image.GetImagesById(id);
            return View(Image);
        }
        public IActionResult Edit(Images Image)
        {
            if (_Image.UpdateImages(Image))
            {
                return RedirectToAction("ShowAll");
            }
            else return BadRequest();
        }
        public IActionResult Delete(Guid id)
        {
            if (_Image.DeleteImages(id))
            {
                return RedirectToAction("ShowAll");
            }
            else return BadRequest();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CodeWebCuaTui/Controllers/ProductController.cs
using CodeWebCuaTui.IServices;
using CodeWebCuaTui.Models;
using CodeWebCuaTui.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using System.Diagnostics.Metrics;

namespace CodeWebCuaTui.Controllers
{
    public class ProductController : Controller
    {
        private readonly ILogger<ProductController> _logger;
        private readonly IProductServices _Product;
        private readonly IColorServices _ColorService;
        private readonly ICategoryServices _CategoryService;
        private readonly ISupplierServices _SupplierService;
        private readonly ISizeServices _SizeService;
        private readonly IImageServices _ImageService;
        private CodeWebCuaTuiDbContex contex;
        public ProductController(ILogger<ProductController> logger)
        {
            _logger = logger;
            _Product = new ProductServices();
            contex = new CodeWebCuaTuiDbContex();
            _ColorService = new ColorServices();
            _CategoryService = new CategoryServices();
            _SupplierService = new SupplierServices();
            _SizeService = new SizeServices();
            _ImageService = new ImagesServices();
        }
        //---------------Product------------
        public IActionResult ShowAll()
        {
            var Product = contex.Product.Include("Color").Include("Images").Include("Sizes").Include("Category")
                .Include("Suppliers").ToList();
            //if(Product!= null)
            //{
            //    var image = contex.Images.FirstOrDefault(i=>i.pro)
            //}    
            //List<Product> Product = _Product.GetAllProducts();

            return View(Product);
        }
        public IActionResult test()
        {
            var Product = contex.Product.Include("Color").Include("Images").Include("Sizes").Include("Category")
                .Include("Suppliers").ToList();
            //if(Product!= null)
            //{
            //    var image = contex.Images.FirstOrDefault(i=>i.pro)
            //}    
            //List<Product> Product = _Product.GetAllProducts();

            return View(Product);
        }
        public IActionResult Details(Guid id)
        {
            CodeWebCuaTuiDbContex contex = new CodeWebCuaTuiDbContex();
            var Product = contex.Product.Find(id);
            return View(Product);
        }
        public IActionResult Create()
        {
            //ViewBag.Colors = new SelectList(contex.Colors.ToList(), "ID", "Name");
            //ViewBag.Categories = new SelectList(contex.Categories.ToList(), "ID", "Name");
            //ViewBag.Suppliers = new SelectList(contex.Suppliers.ToList(), "ID", "Name");
            //ViewBag.Sizes = new SelectList(contex.Sizes.ToList(), "ID", "Name");
            //ViewBag.Images = new SelectList(contex.Images.ToList(), "ID", "Name");
            ViewBag.Colors = new SelectList(_ColorService.GetAllColors(), "ID", "Name");
            ViewBag.Categories = new SelectList(_CategoryService.GetAllCategorys(), "ID", "Name");
            ViewBag.Suppliers = new SelectList(_SupplierService.GetAllSuppliers(), "ID", "Name");
            ViewBag.Sizes = new SelectList(_SizeService.GetAllSizes(), "ID", "Name");
            ViewBag.Images = new SelectList(_ImageService.GetAllImagess(), "ID", "Name");
            return View();
        }
        [HttpPost]
        public IActionResult Create(Product Product)
        {
            if (_Product.CreateProduct(Product))
            {
                TempData["MessageForCreate"] = "Thêm thành công";
                return RedirectToAction("ShowAll");
            }
            else
            {
                TempData["MessageForCreate"] = "Thêm thất bại do sản phẩm trùng tên";
                return RedirectToAction("Create");
            }

        }
        [HttpGet]
        public IActionResult Edit(Guid id)
        {
            ViewBag.Colors = new SelectList(_ColorService.GetAllColors(), "ID", "Name");
            ViewBag.Categories = new SelectList(_CategoryService.GetAllCategorys(), "ID", "Name");
            ViewBag.Suppliers = new SelectList(_SupplierService.GetAllSuppliers(), "ID", "Name");
            ViewBag.Sizes = new SelectList(_SizeService.GetAllSizes(), "ID", "Name");
            ViewBag.Images = new SelectList(_ImageService.GetAllImagess(), "ID", "Name");
            Product Product = _Product.GetProductById(id);
            return View(Product);
        }
        public IActionResult Edit(Product Product)
        {
            ViewBag.Colors = new SelectList(_ColorService.GetAllColors(), "ID", "Name");
            ViewBag.Categories = new SelectList(_CategoryService.GetAllCategorys(), "ID", "Name");
            ViewBag.Suppliers = new SelectList(_SupplierService.GetAllSuppliers(), "ID", "Name");
            ViewBag.Sizes = new SelectList(_SizeService.GetAllSizes(), "ID", "Name");
            ViewBag.Images = new SelectList(_ImageService.GetAllImagess(), "ID", "Name");
            if (_Product.UpdateProduct(Product))
            {
                TempData["AlertMessage"] = "Cập nhật thành công";
                return RedirectToAction("ShowAll");

            }
            else
            {
                TempData["AlertMessage"] = "Sản phẩm trùng tên";
                return View();
            }

        }
        public IActionResult Delete(Guid id)
        {
            if (_Product.DeleteProduct(id))
            {
                return RedirectToAction("ShowAll");
            }
            else return BadRequest();
        }
        public int MyProperty { get; set; }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CodeWebCuaTui/Views/Product/Create.cshtml
@model CodeWebCuaTui.Models.Product

@{
    ViewData["Title"] = "Create";
}

    @if(TempData["MessageForCreate"]!=null)
        {
          <script>
              Swal.fire('@TempData["MessageForCreate"]')
          </script>
        }
<h1>Create</h1>
 
<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ColorID" class="control-label"></label>
             @Html.DropDownListFor(model => model.ColorID, ViewBag.Colors as SelectList, "--Select Color--", new { @class = "form-control" })
                <span asp-validation-for="ColorID" class="text-danger"></span>
            </div>
       
            <div class="form-group">
                <label asp-for="SizeID" class="control-label"></label>
             @Html.DropDownListFor(model => model.SizeID, ViewBag.Sizes as SelectList, "--Select size--", new { @class = "form-control" })
                <span asp-validation-for="SizeID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SupplierID" class="control-label"></label>
               @Html.DropDownListFor(model => model.SupplierID, ViewBag.Suppliers as SelectList, "--Select Supplier--", new { @class = "form-control" })
                <span asp-validation-for="SupplierID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryID" class="control-label"></label>
               @Html.DropDownListFor(model => model.CategoryID, ViewBag.Categories as SelectList, "--Select Category--", new { @class = "form-control" })
                <span asp-validation-for="CategoryID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageID" class="control-label"></label>
                <div style="margin:auto">
                        @Html.DropDownListFor(model => model.ImageID, ViewBag.Images as SelectList, "--Select Images--", new { @class = "form-control" }) 
        <a asp-action="Create" asp-controller="Image">+</a>
                </div>
      
                <span asp-validation-for="ImageID" class="text-danger"></span>
            </div>
           @*    <div class="form-group">
                <label asp-for="ProductCode" class="control-label"></label>
                <input asp-for="ProductCode" class="form-control" />
                <span asp-validation-for="ProductCode" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Describe" class="control-label"></label>
                <input asp-for="Describe" class="form-control" />
                <span asp-validation-for="Describe" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
 
<div>
       <a asp-action="ShowAll">Back to List</a>
</div>

@section Scripts {
@*    <script>
        function showMessage() {
     Swal.fire('@TempData["Message"]')
}
    </script>*@
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CodeWebCuaTui/Views/Product/Delete.cshtml
@model CodeWebCuaTui.Models.Product

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ColorID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ColorID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SizeID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SizeID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SupplierID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SupplierID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CategoryID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CategoryID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Describe)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Describe)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
       <a asp-action="ShowAll">Back to List</a>
    </form>
</div>

CodeWebCuaTui/Views/Product/Details.cshtml
@model CodeWebCuaTui.Models.Product

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ColorID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ColorID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SizeID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SizeID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SupplierID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SupplierID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CategoryID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CategoryID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Describe)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Describe)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id= Model.ID }) |
    <a asp-action="Index">Back to List</a>
</div>

CodeWebCuaTui/Views/Product/ShowAll.cshtml
@model IEnumerable<CodeWebCuaTui.Models.Product>


    <div class="app">
        <div class="layout">
            <!-- Header START -->

            <!-- Header END -->

            <!-- Side Nav START -->

            <!-- Side Nav END -->

            <!-- Page Container START -->
            <div class="container">

                <!-- Content Wrapper START -->
                <div class="main-content">
                    <div class="page-header">
                        <h2 class="header-title">Orders List</h2>
                        <div class="header-sub-title">
                            <nav class="breadcrumb breadcrumb-dash">
                                <a asp-action="Index" asp-controller="Home" class="breadcrumb-item"><i
                                        class="anticon anticon-home m-r-5"></i>Home</a>

                                <span class="breadcrumb-item active">Bill List</span>
                            </nav>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-body">
                            <div class="row m-b-30">
                                <div class="col-lg-8">
                                    <div class="d-md-flex">
                                        <div class="m-b-10 m-r-15">

                                            <select class="custom-select" style="min-width: 180px;">
                                                <option selected>Status</option>
                                                <option value="all">Hoàn thành</option>
                                                <option value="homeDeco">Chưa hoàn thành</option>

                                            </select>
                                          
                                        </div>
                                          <form asp-controller="Home" asp-action="Index">
                                                <div class="input-group" style="width:200px">
                                                    <input type="text" class="form-control" name="searchString"
                                                        placeholder="Tìm kiếm...">

                                                    <div class="input-group-append">
                                                        <button class="btn btn-outline-secondary" type="submit" hidden>
                                                            <i class="fa fa-search"></i>
                                                        </button>
                                                    </div>
                                                </div>
                                            </form>

                                    </div>
                                </div>
                                <div class="col-lg-4 text-right">
                                <a asp-action="Create" asp-controller="Product" style="background-color:black;color:white;border:none"  class="btn btn-primary">
                                    <i class="anticon anticon-plus-circle m-r-5"></i>
                                    <span>Add Product</span>
                                </a>

                                </div>
                            </div>
                            <div class="table-responsive">
                                <table class="table table-hover e-commerce-table">
                                    <table class="table">
    <thead>
        <tr>
 @*           <th>
                @Html.DisplayNameFor(model => model.ID)
            </th>*@

             <th>
                @Html.DisplayNameFor(model => model.ProductCode)
            </th>
              <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.ColorID)*@
                Color
            </th>
            <th>
              @*  @Html.DisplayNameFor(model => model.SizeID)*@
              Size
            </th>
            <th>
               @* @Html.DisplayNameFor(model => model.SupplierID)*@
               Supplier
            </th>
            <th>
             @*   @Html.DisplayNameFor(model => model.CategoryID)*@
             Category
            </th>
            <th>
               @* @Html.DisplayNameFor(model => model.ImageID)*@
               Image
            </th>
           
          
            <th>
                @Html.DisplayNameFor(model => model.Describe)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
                            
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
         @*   <td>
                @Html.DisplayFor(modelItem => item.ID)
            </td>*@ <td>
                @Html.DisplayFor(modelItem => item.ProductCode)
            </td>
               <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Color.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sizes.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Suppliers.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category.Name)
            </td>
            <td>
             @*   @Html.DisplayFor(modelItem => item.Images.Path1)*@
                <img src="@Url.Content(item.Images.Path1)" alt="Hình ảnh" style="width:50px">
            </td>
           
         
            <td>
                @Html.DisplayFor(modelItem => item.Describe)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
            @string.Format("{0:N0}đ", item.Price)
            </td>
            <td>
          @(item.Status == 0 ? "Hoạt động" : "Không hoạt động")
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
                @Html.ActionLink("Details", "Details","Home", new { id=item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.ID })
            </td>
        </tr>
}
    </tbody>
</table>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Content Wrapper END -->

                <!-- Footer START -->
                =
                <!-- Footer END -->

            </div>
            <!-- Page Container END -->

            <!-- Quick View END -->
        </div>
    </div>


    <!-- Core Vendors JS -->